kleister/kleister-api

api/auth.go
router/router.go
shared/token/token.go

Integrated verify api endpoint

---

model/build.go
model/client.go
model/forge.go
model/minecraft.go
model/mod.go
model/pack.go
model/team.go
model/user.go
model/version.go

Check references before delete

---

api/key.go
model/key.go
router/middleware/session/key.go
router/router.go
store/data/key.go
store/data/migration.go
store/key.go
store/store.go

Reintegrated keys API

---

router/router.go

Fixed key routes typo

---

api/key.go
router/router.go

Moved verify to key validation

---

api/key.go
store/client.go
store/data/client.go
store/data/key.go
store/key.go
store/store.go

Correctly fetch key by value

---

store/data/build.go
store/data/client.go
store/data/forge.go
store/data/key.go
store/data/minecraft.go
store/data/mod.go
store/data/pack.go
store/data/solder.go
store/data/team.go
store/data/user.go
store/data/version.go

Tried to make queries safer

---

store/data/migration.go
vendor/github.com/jinzhu/gorm/callback_create.go
vendor/github.com/jinzhu/gorm/main.go
vendor/github.com/jinzhu/gorm/scope.go
vendor/vendor.json

No foreign keys for sqlite3

---

model/build.go
model/pack.go
store/data/forge.go
store/data/migration.go
store/data/minecraft.go

Properly handle nullable columns

---

api/solder.go
model/build.go
model/pack.go
model/solder/build.go
model/solder/index.go
model/solder/mod.go
model/solder/pack.go
model/solder/version.go
router/middleware/session/solder.go
router/router.go

Integrated proper Solder API responses

---

model/pack_background.go
model/pack_icon.go
model/pack_logo.go
model/version_file.go
store/data/migration.go

Properly renamed md5 columns

---

model/solder/index.go
model/solder/mod.go
model/solder/pack.go
model/solder/version.go
store/data/solder.go

More fixes for correct solder API responses

---

model/forge.go
model/minecraft.go

Use the version for minecraft and forge slugs

---

model/build.go

Use the name as a slug for builds

---

model/mod.go
store/data/migration.go

Integrate server/client mod selection

---

api/auth.go
api/build.go
api/client.go
api/forge.go
api/key.go
api/minecraft.go
api/mod.go
api/pack.go
api/profile.go
api/solder.go
api/team.go
api/user.go
api/version.go
main.go
model/minecraft/minecraft.go
store/data/data.go

Improved logging messages

---

model/version_file.go

Validate only zips for version uploads

---

model/version.go

Use the name as a slug for versions

---

model/solder/index.go

Added mirror_url attribute to Solder API

---

store/data/build.go
store/data/version.go

Fixes kleister/kleister-cli#35

Fetch pack for builds and mod for versions

---

router/middleware/session/solder.go

Stop erroring on invalid key/client on solder

---

cmd/server.go
vendor.yml
vendor/github.com/facebookgo/clock/LICENSE
vendor/github.com/facebookgo/clock/README.md
vendor/github.com/facebookgo/clock/clock.go
vendor/github.com/facebookgo/grace/gracehttp/http.go
vendor/github.com/facebookgo/grace/gracenet/net.go
vendor/github.com/facebookgo/grace/license
vendor/github.com/facebookgo/grace/patents
vendor/github.com/facebookgo/grace/readme.md
vendor/github.com/facebookgo/httpdown/httpdown.go
vendor/github.com/facebookgo/httpdown/license
vendor/github.com/facebookgo/httpdown/patents
vendor/github.com/facebookgo/httpdown/readme.md
vendor/github.com/facebookgo/stats/aggregation.go
vendor/github.com/facebookgo/stats/counter.go
vendor/github.com/facebookgo/stats/license
vendor/github.com/facebookgo/stats/patents
vendor/github.com/facebookgo/stats/readme.md
vendor/github.com/facebookgo/stats/stats.go
vendor/github.com/facebookgo/stats/stopper.go

Integrated graceful server restart

---

cmd/server.go
config/config.go
router/middleware/session/acl.go
store/data/data.go

Integrated admin-user and admin-create flags and usage
